server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        auth_basic "Zabbix sample";
        auth_basic_user_file /etc/nginx/.htpasswd;
        default_type text/plain;
        try_files /index.txt =404;
    }

    location /health {
        auth_basic "Zabbix sample";
        auth_basic_user_file /etc/nginx/.htpasswd;
        default_type text/plain;
        try_files /health.txt =404;
    }

    location /status {
        auth_basic "Zabbix sample";
        auth_basic_user_file /etc/nginx/.htpasswd;
        default_type text/plain;
        try_files /status.txt =404;
    }

    location /load-slow {
        auth_basic "Zabbix sample";
        auth_basic_user_file /etc/nginx/.htpasswd;
        default_type text/plain;
        limit_rate 1;
        return 200 "slow connection test data data data data data data data data data data data data data data data data data data data data\n";
    }

    location /nginx_status {
        stub_status; # Enable the stub_status module to provide basic status information about Nginx.
        access_log off; # Disable access logging for this location to reduce log noise.
        allow 127.0.0.1; # Allow access from localhost for monitoring purposes.
        allow 172.18.0.0/16; # Allow access from the Docker Bridge network range for monitoring purposes.
        deny all; # Deny access from all other IP addresses to enhance security.
    }
}
