server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        default_type text/plain;
        return 200 "Welcome to nginx\n";
    }

    location /health {
        default_type text/plain;
        return 200 "OK\n";
    }

    location /status {
        default_type text/plain;
        return 200 "status check\n";
    }

    location /nginx_status {
        stub_status; # Enable the stub_status module to provide basic status information about Nginx.
        access_log off; # Disable access logging for this location to reduce log noise.
        allow 127.0.0.1; # Allow access from localhost for monitoring purposes.
        allow 172.18.0.0/16; # Allow access from the Docker Bridge network range for monitoring purposes.
        deny all; # Deny access from all other IP addresses to enhance security.
    }
}
