UserParameter=nginx.process_count,sh /var/lib/zabbix/user_scripts/nginx_process_count.sh
UserParameter=nginx.active_connections,sh /var/lib/zabbix/user_scripts/nginx_active_connections.sh
UserParameter=nginx.total_requests,sh /var/lib/zabbix/user_scripts/nginx_total_requests.sh
